project_path: .
data_path: data/shakespeare-dialogue.csv
read_format: csv
write_format: parquet
selected_columns: [character] # should include all target column, can include additional columns
target_columns: [character]
return_targets: true
n_cores: 7

group_proportions:
- 0.95
- 0.05
seq_length: 100
max_rows: null