project_path: .
model_name: default-512
read_format: parquet
ddconfig_path: configs/ddconfigs/shakespeare.json

selected_columns: [character] # should include all target column, can include additional columns
target_columns: [character]
target_column_types: # 'criterion' in training_spec must also be adapted
  character: categorical

seq_length: 100
inference_batch_size: 10

export_onnx: true
export_pt: true

model_spec:
  d_model: 512
  nhead: 4
  d_hid: 512
  nlayers: 8
training_spec:
  device: cuda
  epochs: 100
  iter_save: 1
  batch_size: 200
  log_interval: 100
  lr: 0.0001
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    character: CrossEntropyLoss
  optimizer:
    name: AdamW
  scheduler:
    name: CosineAnnealingLR
    T_max: 100
    eta_min: 0.00001
  continue_training: true