project_path: .
model_name: default
read_format: parquet
ddconfig_path: configs/ddconfigs/shakespeare.json

selected_columns: [character] # should include all target column, can include additional columns
target_columns: [character]
target_column_types: # 'criterion' in training_spec must also be adapted
  character: categorical

seq_length: 48
inference_batch_size: 10

export_onnx: true

model_spec:
  d_model: 64
  nhead: 4
  d_hid: 64
  nlayers: 4
training_spec:
  device: mps
  epochs: 100
  iter_save: 5
  batch_size: 500
  log_interval: 10
  lr: 0.0008
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    character: CrossEntropyLoss
  optimizer:
    name: AdamW
  scheduler:
    name: StepLR
    step_size: 1
    gamma: 0.95
  continue_training: false